#!/usr/bin/perl

=head1 NAME

check-snmp-walk - Plugin to check a system simple over snmp.

=head1 SYNOPSIS

    check-snmp-walk [ OPTIONS ]

    check-snmp-walk --help

=head1 REPORTING BUGS

Please report all bugs to <support(at)bloonix.de>.

=head1 AUTHOR

Jonny Schulz <support(at)bloonix.de>.

=head1 POWERED BY

     _    __ _____ _____ __  __ __ __   __
    | |__|  |     |     |  \|  |__|\  \/  /
    |  . |  |  |  |  |  |      |  | >    <
    |____|__|_____|_____|__|\__|__|/__/\__\

=head1 COPYRIGHT

Copyright (C) 2014 by Jonny Schulz. All rights reserved.

=cut

use strict;
use warnings;
use Bloonix::Plugin;

# --------------------------------------------------
# Plugin options
# --------------------------------------------------

my $plugin = Bloonix::Plugin->new(version => "0.2");

$plugin->example(
    description => "Example to check if a VPN connection exists on a Cisco ASA firewall:",
    arguments => [
        host => "127.0.0.1",
        port => 161,
        community => "public",
        oid => "1.3.6.1.4.1.9.9.171.1.2.3.1.7",
        match => "192.168.10.10"
    ]
);

$plugin->has_snmp;

$plugin->add_option(
    name => "The OID to check",
    option => "oid",
    value => "string",
    value_type => "string",
    regex => qr/^[^\s]+\z/,
    mandatory => 1,
    description => "The OID to check."
);

$plugin->add_option(
    name => "Search for a string in the snmp table",
    option => "match",
    value => "regex",
    value_type => "string",
    mandatory => 1,
    description => "A text string that is expected in the SNMP response for the SNMP table that is checked. The string can be a perl regular expression. If the string is not found a CRITICAL status is triggered."
);

# --------------------------------------------------
# Parse options
# --------------------------------------------------

my $opt = $plugin->parse_options;

# --------------------------------------------------
# SNMP connection
# --------------------------------------------------

my $snmp = $plugin->start_snmp_session;

# --------------------------------------------------
# Load statistics
# --------------------------------------------------

my $response = $snmp->get_table($opt->{oid});

if (!defined $response) {
    my $message = "ERROR: ". $snmp->error;
    $snmp->close;
    $plugin->exit(
        status => "CRITICAL",
        message => $message
    );
}

$snmp->close;

# --------------------------------------------------
# Check warning and critical
# --------------------------------------------------

my $status = "OK";
my $value = "string '$opt->{match}' not found";

foreach my $oid (keys %$response) {
    next unless defined $response->{$oid};

    if ($opt->{match} && $response->{$oid} =~ /$opt->{match}/) {
        $value = $response->{$oid};
        last;
    }
}

if (!$value) {
    $status = "CRITICAL";
}

$plugin->exit(
    status => $status,
    message => "SNMP $status: string '$value' found"
);

